version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
          git config --global user.email "frehner@users.noreply.github.com"
          git config --global user.name "CircleCI on behalf of Anthony Frehner"
          echo "machine github.com login frehner password $GITHUB_TOKEN" > ~/.netrc
          cd website && yarn install && GIT_USER=frehner yarn run publish-gh-pages

# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
#       - deploy:
#         requires:
#           - build
#         filters:
#           branches: 
#             only: master
# #         filters: *filter-only-master